name: "bump"
on:
  schedule:
    - cron:  '*/60 * * * *'    # At every 60th minute

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered the original job
          token: ${{ secrets.WORKFLOWS_TOKEN }}
          
      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > tmp/time.txt

      - name: setup git config
        run: |
          git config user.name "DM Bot"
          git config user.email "<skews.inlays_0q@icloud.com>"

      - name: commit
        run: |
          git add tmp/time.txt
          git commit -m "🤖 Trigger a new build"
          git push
