environment:
  nodejs_version: "14"

test_script:
  - node --version
  - npm --version
  - npx @clobbr/cli run -u https://60698fbde1c2a10017544a73.mockapi.io --checks mean=200 median=200 stdDev=200 q5=200 q50=200 q95=200 q99=200 pctOfSuccess=95

build: off
