name: bump
'on':
  schedule:
    - cron: '*/60 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > tmp/time.txt
      - name: setup git config
        run: |

          git config user.name "DM Bot"
          git config user.email "<skews.inlays_0q@icloud.com>"
      - name: commit
        run: "# Stage the file, commit and push\ngit add time.txt\ngit commit -m \"\U0001F916 Trigger a new build\"\ngit push origin master\n"
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.WORKFLOWS_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: b16146eb8a7e5e7fb4df8ceb46b06765c82aa20c
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/.schedule-bump-b16146eb8a7e5e7fb4df8ceb46b06765c82aa20c.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
