name: bump
'on':
  schedule:
    - cron: '*/60 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'
          token: '${{ secrets.WORKFLOWS_TOKEN }}'
      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > tmp/time.txt
      - name: setup git config
        run: |
          git config user.name "DM Bot"
          git config user.email "<skews.inlays_0q@icloud.com>"
      - name: commit
        run: "git add tmp/time.txt\ngit commit -m \"\U0001F916 Trigger a new build\"\ngit push\n"
    env:
      DELAYED_JOB_CHECKOUT_REF: 168245fba51440c2b72d00545173ad807e7b3f36
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/.schedule-bump-168245fba51440c2b72d00545173ad807e7b3f36.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
